version: "3.9"
services:
  vision: 
    build: .
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vision
    ports:
      - "4000:4000"
